plugins {
    id 'application'
}

dependencies {
    implementation project(':raft-rpc')
    implementation 'io.grpc:grpc-netty-shaded:1.62.2'
    implementation 'io.grpc:grpc-protobuf:1.62.2'
    implementation 'io.grpc:grpc-stub:1.62.2'
}

application {
    mainClass = 'raftkv.client.RaftCliClient'
}
